[package]
name = "habitglo"
version = "0.1.0"
description = "HabitGlo desktop shell"
authors = ["HabitGlo"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.5", features = [ "api-all", "system-tray" ] }
winapi = { version = "0.3", features = ["winuser", "shellapi", "commctrl", "minwindef"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25"
objc = "0.2"
